name: UpgradeEnergy

on:
  push:
    branches:
      - 'main'
jobs:

  basic-ubuntu-20:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # run pyinstaller
      - name: Run pyinstaller
        run: |
          pyinstaller --onefile --noconsole main.py